export const dummyItems = [
  {
    id: 1,
    itemName: "Laptop",
    brand: "Dell",
    model: "XPS 13",
    color: "Silver",
    price: 1200.99,
  },
  {
    id: 2,
    itemName: "Smartphone",
    brand: "Samsung",
    model: "Galaxy S21",
    color: "Black",
    price: 899.99,
  },
  {
    id: 3,
    itemName: "Headphones",
    brand: "Sony",
    model: "WH-1000XM4",
    color: "Black",
    price: 349.99,
  },
  {
    id: 4,
    itemName: "Camera",
    brand: "Canon",
    model: "EOS R5",
    color: "Black",
    price: 3499.99,
  },
  {
    id: 5,
    itemName: "Smartwatch",
    brand: "Apple",
    model: "Watch Series 7",
    color: "Gold",
    price: 399.99,
  },
  {
    id: 6,
    itemName: "Gaming Console",
    brand: "Microsoft",
    model: "Xbox Series X",
    color: "Black",
    price: 499.99,
  },
  {
    id: 7,
    itemName: "Tablet",
    brand: "Samsung",
    model: "Galaxy Tab S7",
    color: "Silver",
    price: 649.99,
  },
  {
    id: 8,
    itemName: "Fitness Tracker",
    brand: "Fitbit",
    model: "Charge 5",
    color: "Blue",
    price: 149.99,
  },
];
